spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-route # ????????????? ????????
          uri: lb://user-service # ?????, ?? ??????? ????? ???????????? ???????, ??????????????? ??????? ????????
          predicates:
            - Path=/api/v1/user/**   #???????, ????????????, ????? ??????????? ?????? ???????
        - id: company-service-route
          uri: lb://company-service
          predicates:
            - Path=/api/v1/company/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082
logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"

