server:
  port: ${PROPERTIES_SERVER_PORT}
spring:
  application:
    name: configuration-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  kafka:
    bootstrap-servers: localhost:9092