server:
  port: 8081
microservice:
  name: Company Service
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/microservices?currentSchema=company-schema
    username: user
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka