version: '3.7'

services:
  db:
    image: postgres:15.4
    container_name: microservices-sql-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -D ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 25
    ports:
      - "5433:5432"
    volumes:
      - ./db_microservices_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_connections=400"]
volumes:
  db_microservices_data: {}