###Получить информацию о сервисе company-service
GET http://localhost:8082/api/v1/company/get-description

###Получение списка всех компаний ( с ФИО директора)
GET http://localhost:8082/api/v1/company/get-companies

###Создание компании (должна быть синхронная проверка из user-service, на существование директора.
#Если директора не существует – кидать 404 ошибку с соответствующим сообщением)
POST http://localhost:8082/api/v1/company/create-company
Content-Type: application/json

{
  "name": "Company 2",
  "msrn": 222221,
  "description": "Company 2 description",
  "userId": 2
}

###Проверка существования компании по ее идентификатору. Параметры: 1. id
GET http://localhost:8082/api/v1/company/exist-company/1

###Получение информации о компании. Параметры: 1. id
GET http://localhost:8082/api/v1/company/get-company/2
